### ISSUE TITLE
First time it is not translating

### ISSUE THREAD

**Issue by hiteshjangid** [DenisCarriere/Leaflet.draw.locales#16]
My language is set to Dutch but at very first time if I select a tool to draw the shape the tooltip is showing with English translation. ( **Click Map to place Marker**). But after that the trasnlation is working good.
![Screenshot_](https://user-images.githubusercontent.com/18675507/80961399-8803ae00-8e28-11ea-85e3-c13c71235ecc.png)

**Comment by DenisCarriere** [comment]
You need to define your language before you create your Leaflet draw object, that might be the issue.

have a look at this example:

https://github.com/DenisCarriere/Leaflet.draw.locales/blob/master/examples/basic.js

**Comment by DenisCarriere** [comment]
@hiteshjangid Try doing the following, add the `drawLocales` before & after the draw items

```js
// LeafletDraw.Locales
drawLocales("nl")

// Leaflet.Draw
const drawnItems = L.featureGroup().addTo(map);

// re-trigger LeafletDraw.Locales
drawLocales("nl")
```
