### ISSUE TITLE
non english characters are not showing

### ISSUE THREAD

**Issue by mejiafabiandj** [DenisCarriere/Leaflet.draw.locales#4]
![image](https://user-images.githubusercontent.com/3708192/47606282-69249000-d9d7-11e8-8a01-6025592076c9.png)

this is my code 
```
var drawLocales = require('leaflet-draw-locales');

// Customize locale language
var locale = drawLocales('es');
locale.draw.toolbar.buttons.polygon = 'Awesome polygon!';
L.drawLocal = locale;
```

**Comment by DenisCarriere** [comment]
Seems like the Spanish translations is working on my side

This might be an UFT-8 issue on the browser side

![image](https://user-images.githubusercontent.com/550895/61796887-97c87d80-ae26-11e9-8452-d005862f6ce8.png)
